name: "Enhancement"
description: "Suggest improvements or optimizations to existing code."
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a refactor or enhancement. Improving code quality and performance benefits the entire project.

  - type: markdown
    attributes:
      value: |
        Before submitting a new request, **please check the issue tracker** to ensure it hasn't already been proposed.

  - type: textarea
    id: improvement-summary
    attributes:
      label: Summary of Improvement
      description: |
        Briefly describe the improvement or refactor needed in the Next.js autonomous vehicle simulation project.

        **Example:**
        "Optimize the procedural environment generator for faster scene loads."
        "Improve the path-planning module to reduce route oscillations."
    validations:
      required: true

  - type: textarea
    id: current-implementation
    attributes:
      label: Current Implementation
      description: |
        Describe how the current implementation works today and where it falls short for the simulation.

        **Example:**
        "The terrain generator runs on the client and blocks the UI thread during initialization."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: |
        Explain the changes you recommend to improve or refactor the existing setup.

        **Example:**
        "Move environment generation to an API route and stream assets progressively."
    validations:
      required: true
